# Generated by Django 2.0 on 2018-08-09 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_mturk', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Worker_Block_Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_blocks_project', to='api.Project')),
                ('fk_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_blocks_project', to='api.Worker')),
            ],
        ),
    ]
