# Generated by Django 2.0 on 2018-08-09 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='id_mturk',
            new_name='id_worker',
        ),
    ]
