# Generated by Django 2.0 on 2018-08-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_project_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account_Mturk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('key_access', models.CharField(max_length=200)),
                ('key_secret', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'MTurk Account',
            },
        ),
    ]
