# Generated by Django 2.0 on 2018-08-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_account_mturk'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker_block_project',
            name='is_sandbox',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
