# Generated by Django 2.0 on 2018-08-23 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_worker_block_project_is_sandbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='Count_Assignments_Worker_Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_assignments', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='count_assignments_max_per_worker',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='count_assignments_worker_project',
            name='fk_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='count_assignments', to='api.Project'),
        ),
        migrations.AddField(
            model_name='count_assignments_worker_project',
            name='fk_worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='count_assignments', to='api.Worker'),
        ),
    ]
