# Generated by Django 2.0 on 2018-08-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180823_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment_Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_worker', models.CharField(max_length=200)),
                ('id_assignment', models.CharField(max_length=200)),
            ],
        ),
    ]
