# Generated by Django 2.0 on 2018-08-24 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_assignment_worker'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignment_worker',
            unique_together={('id_worker', 'id_assignment')},
        ),
    ]
