# Generated by Django 2.0 on 2018-09-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180824_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_assignment', models.CharField(max_length=200)),
                ('status_external', models.IntegerField(choices=[(0, 'APPROVED'), (1, 'REJECTED'), (2, 'SUBMITTED'), (3, 'APPROVED_OVERRIDE')])),
                ('status_internal', models.IntegerField(choices=[(0, 'APPROVED'), (1, 'REJECTED')], null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='count_assignments_worker_project',
            unique_together={('fk_project', 'fk_worker')},
        ),
    ]
