# Generated by Django 2.0 on 2018-09-12 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180912_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='datetime_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
