# Generated by Django 2.0 on 2018-09-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_assignment_datetime_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='id_assignment',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
