# Generated by Django 2.0 on 2018-09-14 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20180912_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Settings_Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('reward', models.CharField(default='0.0', max_length=10)),
                ('count_assignments', models.IntegerField(default=1)),
                ('count_assignments_max_per_worker', models.IntegerField(default=-1)),
                ('lifetime', models.IntegerField(default=604800)),
                ('duration', models.IntegerField(default=3600)),
                ('block_workers', models.BooleanField(default=False)),
                ('has_content_adult', models.BooleanField(default=False)),
                ('qualification_assignments_approved', models.IntegerField(null=True)),
                ('qualification_hits_approved', models.IntegerField(null=True)),
                ('qualification_locale', models.TextField(null=True)),
                ('keywords', models.ManyToManyField(related_name='projects', to='api.Keyword')),
            ],
        ),
        migrations.CreateModel(
            name='Template_Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('template', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Template_Hit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('template', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Template_Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('template', models.TextField()),
                ('height_frame', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('json_dict_parameters', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='count_assignments_max_per_worker',
        ),
        migrations.AddField(
            model_name='project',
            name='fk_account_mturk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='api.Account_Mturk'),
        ),
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(default='default_name', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='version',
            field=models.IntegerField(default=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template_worker',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates_worker', to='api.Project'),
        ),
        migrations.AddField(
            model_name='template_worker',
            name='template_assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates_used', to='api.Template_Assignment'),
        ),
        migrations.AddField(
            model_name='template_worker',
            name='template_hit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates_used', to='api.Template_Hit'),
        ),
        migrations.AddField(
            model_name='template_hit',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates_hit', to='api.Project'),
        ),
        migrations.AddField(
            model_name='template_assignment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates_assignment', to='api.Project'),
        ),
        migrations.AddField(
            model_name='settings_batch',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings_batch', to='api.Project'),
        ),
        migrations.AddField(
            model_name='settings_batch',
            name='template_worker',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_batch', to='api.Template_Worker'),
        ),
        migrations.AlterUniqueTogether(
            name='template_worker',
            unique_together={('project', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='template_hit',
            unique_together={('project', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='template_assignment',
            unique_together={('project', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='settings_batch',
            unique_together={('project', 'name')},
        ),
    ]
