# Generated by Django 2.0 on 2018-09-15 19:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20180914_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='datetime_visited',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
