# Generated by Django 2.0 on 2018-09-17 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_project_datetime_visited'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='settings_batch_default',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_default', to='api.Settings_Batch'),
        ),
    ]
