# Generated by Django 2.0 on 2018-09-24 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20180920_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings_batch',
            name='template_worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_batch', to='api.Template_Worker'),
        ),
    ]
