# Generated by Django 2.0 on 2018-09-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20180924_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings_batch',
            name='count_assignments_max_per_worker',
            field=models.IntegerField(null=True),
        ),
    ]
