# Generated by Django 2.0 on 2018-09-27 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20180924_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('settings_batch_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Settings_Batch')),
            ],
            bases=('api.settings_batch',),
        ),
        migrations.CreateModel(
            name='HIT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_hit', models.CharField(max_length=200, unique=True)),
                ('datetime_creation', models.DateTimeField()),
                ('datetime_expiration', models.DateTimeField()),
                ('parameters', models.TextField()),
                ('count_assignments_additional', models.IntegerField(default=0)),
                ('fk_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hits', to='api.Batch')),
            ],
        ),
        migrations.AlterField(
            model_name='template_assignment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_template_assignment_related', to='api.Project'),
        ),
        migrations.AlterField(
            model_name='template_hit',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_template_hit_related', to='api.Project'),
        ),
        migrations.AlterField(
            model_name='template_worker',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_template_worker_related', to='api.Project'),
        ),
    ]
