# Generated by Django 2.0 on 2018-09-27 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20180927_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hit',
            old_name='fk_batch',
            new_name='batch',
        ),
    ]
