# Generated by Django 2.0 on 2018-09-27 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20180927_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='use_sandbox',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
