# Generated by Django 2.0 on 2018-09-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_batch_use_sandbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='name1',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
