# Generated by Django 2.0 on 2018-09-28 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_batch_name1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='settings_batch_ptr',
        ),
        migrations.RemoveField(
            model_name='hit',
            name='batch',
        ),
        migrations.DeleteModel(
            name='Batch',
        ),
    ]
