# Generated by Django 2.0 on 2018-09-28 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20180928_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('use_sandbox', models.BooleanField()),
                ('settings_batch', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch', to='api.Settings_Batch')),
            ],
        ),
    ]
