# Generated by Django 2.0 on 2018-09-28 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_batch_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='hit',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hits', to='api.Batch'),
        ),
    ]
