# Generated by Django 2.0 on 2018-10-04 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_hit_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='hit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.HIT'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.Worker'),
        ),
    ]
