# Generated by Django 2.0 on 2018-10-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20181004_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='answer',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
