# Generated by Django 2.0 on 2018-10-06 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_assignment_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='hit',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.HIT'),
            preserve_default=False,
        ),
    ]
