# Generated by Django 2.0 on 2018-10-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20181006_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status_external',
            field=models.IntegerField(choices=[(0, 'APPROVED'), (1, 'REJECTED'), (2, 'SUBMITTED'), (3, 'APPROVED_OVERRIDE')], null=True),
        ),
    ]
