# Generated by Django 2.0 on 2018-10-12 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20181006_1042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worker',
            options={'ordering': ['id_worker']},
        ),
        migrations.AddField(
            model_name='worker',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='api.Project'),
        ),
        migrations.AlterUniqueTogether(
            name='worker',
            unique_together={('id_worker', 'project')},
        ),
    ]
