# Generated by Django 2.0 on 2018-10-19 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20181012_0547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker_block_project',
            old_name='fk_project',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='worker_block_project',
            old_name='fk_worker',
            new_name='worker',
        ),
        migrations.RemoveField(
            model_name='worker_block_project',
            name='is_sandbox',
        ),
        migrations.AlterUniqueTogether(
            name='worker',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='worker',
            name='project',
        ),
    ]
