# Generated by Django 2.0 on 2018-10-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20181019_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='is_blocked_global',
            field=models.BooleanField(default=False),
        ),
    ]
