# Generated by Django 2.0 on 2018-10-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20181020_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings_batch',
            name='reward',
            field=models.IntegerField(default=0),
        ),
    ]
