# Generated by Django 2.0 on 2018-10-28 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20181026_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='settings_batch',
        ),
        migrations.AddField(
            model_name='settings_batch',
            name='batch',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings_batch', to='api.Batch'),
        ),
    ]
