# Generated by Django 2.0 on 2018-11-04 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20181031_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message_Reject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1024)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='message_reject_default',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='api.Message_Reject'),
        ),
    ]
