# Generated by Django 2.0 on 2018-11-04 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20181104_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message_reject',
            name='message',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
