# Generated by Django 2.0 on 2018-12-12 21:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_auto_20181108_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='datetime_update',
        ),
        migrations.AddField(
            model_name='assignment',
            name='datetime_accept',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='datetime_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='assignment',
            name='datetime_submit',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='datetime_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='project',
            name='datetime_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='template_assignment',
            name='datetime_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='template_global',
            name='datetime_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='template_hit',
            name='datetime_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='template_worker',
            name='datetime_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='project',
            name='datetime_visited',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='template_worker',
            name='template_hit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates_used', to='api.Template_HIT'),
        ),
    ]
