# Generated by Django 2.0 on 2018-12-10 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_auto_20181202_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='datetime_accept',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='datetime_submit',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='template_worker',
            name='template_hit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates_used', to='api.Template_HIT'),
        ),
    ]
