# Generated by Django 2.0 on 2018-12-12 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_auto_20181212_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template_worker',
            name='template_hit',
        ),
    ]
