# Generated by Django 2.0 on 2018-12-12 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_remove_template_worker_template_hit'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='template_hit',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='template_hit',
            name='project',
        ),
        migrations.DeleteModel(
            name='Template_Hit',
        ),
    ]
