# Generated by Django 2.0 on 2018-12-12 21:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_auto_20181212_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template_HIT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('template', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('datetime_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_template_hit_related', to='api.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='template_hit',
            unique_together={('project', 'name')},
        ),
    ]
