# Generated by Django 2.0 on 2019-03-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_auto_20190111_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='amount_budget_max',
            field=models.IntegerField(null=True),
        ),
    ]
