# Generated by Django 2.0 on 2019-04-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_hit_count_assignments_dead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hit',
            name='datetime_expiration',
            field=models.DateTimeField(db_index=True),
        ),
    ]
