# Generated by Django 2.2.1 on 2019-05-11 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('api', '0050_auto_20190414_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageApprove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1024)),
                ('message_lowercase', models.CharField(max_length=1024, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1024)),
                ('message_lowercase', models.CharField(max_length=1024, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='Message_Reject',
            new_name='MessageReject',
        ),
        migrations.CreateModel(
            name='ReasonToProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reason_to_project', to='api.Project')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reason_to_project', to='api.Reason')),
            ],
            options={
                'unique_together': {('project', 'reason')},
            },
        ),
        migrations.CreateModel(
            name='MessageRejectToProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_reject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_reject_to_project', to='api.MessageReject')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_reject_to_project', to='api.Project')),
            ],
            options={
                'unique_together': {('project', 'message_reject')},
            },
        ),
        migrations.CreateModel(
            name='MessageApproveToProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_approve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_approve_to_project', to='api.MessageApprove')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_approve_to_project', to='api.Project')),
            ],
            options={
                'unique_together': {('project', 'message_approve')},
            },
        ),
    ]
