# Generated by Django 2.2.1 on 2019-05-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_auto_20190511_1323'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='messagerejecttoproject',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='messagerejecttoproject',
            name='message_reject',
        ),
        migrations.RemoveField(
            model_name='messagerejecttoproject',
            name='project',
        ),
        migrations.AlterUniqueTogether(
            name='reasontoproject',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='reasontoproject',
            name='project',
        ),
        migrations.RemoveField(
            model_name='reasontoproject',
            name='reason',
        ),
        migrations.AddField(
            model_name='messageapprove',
            name='projects',
            field=models.ManyToManyField(related_name='messages_approve', to='api.Project'),
        ),
        migrations.AddField(
            model_name='messagereject',
            name='projects',
            field=models.ManyToManyField(related_name='messages_reject', to='api.Project'),
        ),
        migrations.AddField(
            model_name='reason',
            name='projects',
            field=models.ManyToManyField(related_name='messages_reason', to='api.Project'),
        ),
        migrations.DeleteModel(
            name='MessageApproveToProject',
        ),
        migrations.DeleteModel(
            name='MessageRejectToProject',
        ),
        migrations.DeleteModel(
            name='ReasonToProject',
        ),
    ]
