# Generated by Django 2.2.1 on 2019-07-09 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_auto_20190514_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=100)),
                ('status', models.IntegerField(choices=[(0, 'CREATED')], null=True)),
                ('datetime_created', models.DateTimeField()),
                ('datetime_started', models.DateTimeField()),
                ('datetime_finished', models.DateTimeField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='celery_tasks', to='api.Project')),
            ],
        ),
    ]
