# Generated by Django 2.2.1 on 2019-07-09 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_celerytasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='celerytasks',
            name='description',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
