# Generated by Django 2.2.1 on 2019-07-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_auto_20190713_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='celerytasks',
            name='payload',
            field=models.TextField(null=True),
        ),
    ]
