# Generated by Django 2.2.1 on 2019-07-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_celerytasks_payload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celerytasks',
            name='status',
            field=models.IntegerField(choices=[(0, 'CREATED'), (1, 'PROGRESS'), (2, 'FINISHED'), (3, 'FAILED')]),
        ),
    ]
