# Generated by Django 2.2.1 on 2019-07-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_auto_20190714_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='template_worker',
            name='is_fixed',
            field=models.BooleanField(default=False),
        ),
    ]
