# Generated by Django 2.2.1 on 2019-08-02 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_template_worker_is_fixed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template_worker',
            name='is_fixed',
        ),
        migrations.AddField(
            model_name='template_worker',
            name='template_original',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='api.Template_Worker'),
        ),
    ]
