# Generated by Django 2.2.4 on 2019-08-16 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_auto_20190802_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='fk_account_mturk',
        ),
        migrations.DeleteModel(
            name='Account_Mturk',
        ),
    ]
