# Generated by Django 3.0.8 on 2020-07-24 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_auto_20190816_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageapprove',
            name='message_lowercase',
        ),
        migrations.RemoveField(
            model_name='messagereject',
            name='message_lowercase',
        ),
        migrations.RemoveField(
            model_name='reason',
            name='message_lowercase',
        ),
    ]
