version: '3.7'

services:
  backend:
    build: .
    container_name: mturk-manager-backend-${VERSION_MTURK_MANAGER}
    image: mturk-manager-backend:${VERSION_MTURK_MANAGER}
    env_file:
      - ../.env
    depends_on:
      - db
      - rabbitmq
    ports:
      - 8004:8000

  db:
    image: postgres:10
    container_name: mturk-manager-database-${VERSION_MTURK_MANAGER}
    env_file:
      - ../.env
    volumes:
      - type: bind
        source: ${PATH_DATABASE_DATA}
        target: /var/lib/postgresql/data/
    ports:
      - 5432:5432

  rabbitmq:
    image: rabbitmq:3-management
    container_name: mturk-manager-rabbitmq-${VERSION_MTURK_MANAGER}
    ports:
      - 5672:5672

  celery:
    build: .
    container_name: mturk-manager-worker-${VERSION_MTURK_MANAGER}
    image: mturk-manager-backend:${VERSION_MTURK_MANAGER}
    command: /venv/bin/celery -A mturk_db worker -l info --concurrency=1
    environment:
      - C_FORCE_ROOT=true
    env_file:
      - ../.env
    depends_on:
      - rabbitmq