# Generated by Django 2.0 on 2018-02-08 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='m_Account_Mturk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('key_access', models.CharField(max_length=200)),
                ('key_secret', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='m_Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_assignment', models.CharField(max_length=200, unique=True)),
                ('answer', models.TextField()),
                ('corpus_viewer_tags', models.ManyToManyField(related_name='corpus_viewer_items', to='viewer.m_Tag')),
            ],
            options={
                'ordering': ['fk_hit'],
            },
        ),
        migrations.CreateModel(
            name='m_Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('keywords', models.TextField()),
                ('count_assignments', models.IntegerField()),
                ('use_sandbox', models.BooleanField(default=True)),
                ('reward', models.CharField(max_length=10)),
                ('lifetime', models.IntegerField()),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='m_Hit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_hit', models.CharField(max_length=200, unique=True)),
                ('parameters', models.TextField()),
                ('fk_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hits', to='mturk_manager.m_Batch')),
            ],
        ),
        migrations.CreateModel(
            name='m_Message_Reject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='m_Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('name', models.CharField(max_length=200, unique=True)),
                ('title', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('keywords', models.TextField(default='')),
                ('count_assignments', models.IntegerField(default=1)),
                ('reward', models.CharField(default='0.0', max_length=10)),
                ('lifetime', models.IntegerField(default=604800)),
                ('duration', models.IntegerField(default=3600)),
                ('use_sandbox', models.BooleanField(default=True)),
                ('fk_account_mturk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='mturk_manager.m_Account_Mturk')),
                ('fk_message_reject_default', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='mturk_manager.m_Message_Reject')),
            ],
        ),
        migrations.CreateModel(
            name='m_Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('template', models.TextField()),
                ('height_frame', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('fk_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='mturk_manager.m_Project')),
            ],
        ),
        migrations.CreateModel(
            name='m_Template_Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('template', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('fk_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates_assignment', to='mturk_manager.m_Project')),
            ],
        ),
        migrations.CreateModel(
            name='m_Template_Hit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('template', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('fk_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates_hit', to='mturk_manager.m_Project')),
            ],
        ),
        migrations.CreateModel(
            name='m_Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='m_template',
            name='fk_template_assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates_used', to='mturk_manager.m_Template_Assignment'),
        ),
        migrations.AddField(
            model_name='m_template',
            name='fk_template_hit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates_used', to='mturk_manager.m_Template_Hit'),
        ),
        migrations.AddField(
            model_name='m_project',
            name='fk_template_assignment_main',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='mturk_manager.m_Template_Assignment'),
        ),
        migrations.AddField(
            model_name='m_project',
            name='fk_template_hit_main',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='mturk_manager.m_Template_Hit'),
        ),
        migrations.AddField(
            model_name='m_project',
            name='fk_template_main',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='mturk_manager.m_Template'),
        ),
        migrations.AddField(
            model_name='m_message_reject',
            name='fk_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_reject', to='mturk_manager.m_Project'),
        ),
        migrations.AddField(
            model_name='m_batch',
            name='fk_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='mturk_manager.m_Project'),
        ),
        migrations.AddField(
            model_name='m_batch',
            name='fk_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='mturk_manager.m_Template'),
        ),
        migrations.AddField(
            model_name='m_assignment',
            name='fk_hit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='mturk_manager.m_Hit'),
        ),
        migrations.AddField(
            model_name='m_assignment',
            name='fk_worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='mturk_manager.m_Worker'),
        ),
        migrations.AlterUniqueTogether(
            name='m_template_hit',
            unique_together={('name', 'fk_project')},
        ),
        migrations.AlterUniqueTogether(
            name='m_template_assignment',
            unique_together={('name', 'fk_project')},
        ),
        migrations.AlterUniqueTogether(
            name='m_template',
            unique_together={('name', 'fk_project')},
        ),
        migrations.AlterUniqueTogether(
            name='m_batch',
            unique_together={('name', 'fk_project')},
        ),
    ]
