# Generated by Django 2.0 on 2017-12-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mturk_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_project',
            name='template',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
