# Generated by Django 2.0 on 2017-12-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mturk_manager', '0002_m_project_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='m_MTurk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('key_access', models.CharField(max_length=200)),
                ('key_secret', models.CharField(max_length=200)),
            ],
        ),
    ]
