# Generated by Django 2.0 on 2018-02-13 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mturk_manager', '0002_auto_20180208_1401'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='m_worker',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='m_worker',
            name='fk_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='mturk_manager.m_Project'),
        ),
        migrations.AddField(
            model_name='m_worker',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='m_worker',
            unique_together={('name', 'fk_project')},
        ),
    ]
