# Generated by Django 2.0 on 2017-12-19 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mturk_manager', '0003_m_mturk'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='m_MTurk',
            new_name='m_Account_Mturk',
        ),
    ]
