# Generated by Django 2.0 on 2018-02-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
        ('mturk_manager', '0004_auto_20180214_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_worker',
            name='corpus_viewer_tags',
            field=models.ManyToManyField(related_name='corpus_viewer_workers', to='viewer.m_Tag'),
        ),
    ]
