# Generated by Django 2.0 on 2017-12-19 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mturk_manager', '0004_auto_20171219_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_project',
            name='fk_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mturk_manager.m_Account_Mturk'),
        ),
    ]
