# Generated by Django 2.0 on 2017-12-19 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mturk_manager', '0005_m_project_fk_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='m_project',
            old_name='fk_account',
            new_name='fk_account_mturk',
        ),
    ]
