# Generated by Django 2.0 on 2018-02-26 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mturk_manager', '0006_m_template_json_dict_parameters'),
    ]

    operations = [
        migrations.CreateModel(
            name='m_Message_Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='m_project',
            name='block_workers',
            field=models.CharField(default='disabled', max_length=20),
        ),
        migrations.AddField(
            model_name='m_message_block',
            name='fk_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_block', to='mturk_manager.m_Project'),
        ),
        migrations.AddField(
            model_name='m_project',
            name='fk_message_block_default',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='mturk_manager.m_Message_Block'),
        ),
    ]
