# Generated by Django 2.0 on 2017-12-19 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mturk_manager', '0006_auto_20171219_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='m_Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='m_Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='m_Hit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hits', to='mturk_manager.m_Batch')),
            ],
        ),
        migrations.CreateModel(
            name='m_Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('fk_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='mturk_manager.m_Assignment')),
            ],
        ),
        migrations.AlterField(
            model_name='m_project',
            name='fk_account_mturk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='mturk_manager.m_Account_Mturk'),
        ),
        migrations.AddField(
            model_name='m_batch',
            name='fk_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='mturk_manager.m_Project'),
        ),
        migrations.AddField(
            model_name='m_assignment',
            name='fk_hit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='mturk_manager.m_Hit'),
        ),
    ]
