# Generated by Django 2.0 on 2017-12-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mturk_manager', '0007_auto_20171219_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_assignment',
            name='is_approved',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='m_assignment',
            name='was_approved',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
