# Generated by Django 2.0 on 2018-03-11 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mturk_manager', '0008_m_assignment_reviewer_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_batch',
            name='fk_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='mturk_manager.m_Template'),
        ),
    ]
