# Generated by Django 2.0 on 2018-04-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mturk_manager', '0010_auto_20180312_1624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='m_account_mturk',
            options={'verbose_name': 'MTurk Account'},
        ),
        migrations.AlterModelOptions(
            name='m_project',
            options={'verbose_name': 'Project'},
        ),
        migrations.AddField(
            model_name='m_project',
            name='has_content_adult',
            field=models.BooleanField(default=False),
        ),
    ]
