# Generated by Django 2.0 on 2018-05-11 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mturk_manager', '0011_auto_20180419_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_hit',
            name='count_assignments_additional',
            field=models.IntegerField(default=0),
        ),
    ]
