# Generated by Django 2.0 on 2018-06-16 15:07

from django.db import migrations, models
from django.utils.text import slugify

def migrate_data_forward(apps, schema_editor):
    m_Project = apps.get_model('mturk_manager', 'm_project')
    for instance in m_Project.objects.all():
        print('Generating slug for {}'.format(instance.name))
        instance.slug = slugify(instance.name)
        instance.save()

def migrate_data_backward(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('mturk_manager', '0012_m_hit_count_assignments_additional'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_project',
            name='slug',
            field=models.SlugField(null=True, max_length=200, unique=True),
        ),
        migrations.RunPython(
            migrate_data_forward,
            migrate_data_backward,
        ),
    ]
