# Generated by Django 2.0 on 2018-06-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mturk_manager', '0015_model_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_project',
            name='qualification_assignments_approved',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='m_project',
            name='qualification_locale',
            field=models.TextField(null=True),
        ),
    ]
