# Generated by Django 2.0 on 2018-07-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mturk_manager', '0016_auto_20180625_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_project',
            name='qualification_hits_approved',
            field=models.IntegerField(null=True),
        ),
    ]
