# Generated by Django 2.0 on 2018-07-31 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mturk_manager', '0017_m_project_qualification_hits_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='m_worker',
            old_name='is_blocked',
            new_name='is_blocked_hard',
        ),
        migrations.AddField(
            model_name='m_worker',
            name='is_blocked_soft',
            field=models.BooleanField(default=False),
        ),
    ]
