# Generated by Django 2.0 on 2018-07-31 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mturk_manager', '0018_auto_20180731_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_worker',
            name='is_blocked_hard',
        ),
        migrations.RemoveField(
            model_name='m_worker',
            name='is_blocked_soft',
        ),
        migrations.AddField(
            model_name='m_worker',
            name='is_blocked',
            field=models.IntegerField(choices=[(1, 'NONE'), (2, 'SOFT'), (3, 'HARD')], default=1),
        ),
    ]
