# Generated by Django 2.0 on 2018-08-03 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mturk_manager', '0019_auto_20180731_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_worker',
            name='is_blocked',
        ),
    ]
