# Generated by Django 2.0 on 2018-08-10 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mturk_manager', '0020_remove_m_worker_is_blocked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Global_DB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('token_instance', models.CharField(max_length=200)),
                ('token_worker', models.CharField(max_length=200)),
            ],
        ),
    ]
