# Generated by Django 2.0 on 2018-08-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mturk_manager', '0021_global_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='m_project',
            name='keywords',
        ),
        migrations.AddField(
            model_name='m_project',
            name='keywords',
            field=models.ManyToManyField(related_name='projects', to='mturk_manager.Keyword'),
        ),
    ]
