# Generated by Django 2.0 on 2018-08-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mturk_manager', '0023_auto_20180818_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_batch',
            name='keywords',
        ),
        migrations.AddField(
            model_name='m_batch',
            name='keywords',
            field=models.ManyToManyField(related_name='batches', to='mturk_manager.Keyword'),
        ),
    ]
