# Generated by Django 2.0 on 2018-08-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mturk_manager', '0024_auto_20180818_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_project',
            name='assignments_max_per_worker',
            field=models.IntegerField(default=-1),
        ),
    ]
