# Generated by Django 2.0 on 2018-08-23 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mturk_manager', '0025_m_project_assignments_max_per_worker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_project',
            name='assignments_max_per_worker',
        ),
    ]
