from .config import Manager_Config
from .keywords import Manager_Keywords
from .messages_reject import Manager_Messages_Reject
from .batches import Manager_Batches
from .workers import Manager_Workers
from .projects import Manager_Projects
from .settings_batch import Manager_Settings_Batch
from .templates_worker import Manager_Templates_Worker
from .templates_assignment import Manager_Templates_Assignment
from .templates_hit import Manager_Templates_HIT
from .templates_global import Manager_Templates_Global
from .assignments import Manager_Assignments
from .hits import Manager_HITs
from .finances import Manager_Finances
